export const ON_AUTH_START = "ON_AUTH_START";
export const ON_AUTH_SUCCESS = "ON_AUTH_SUCCESS";
export const ON_AUTH_FAIL = "ON_AUTH_FAIL";
export const ON_AUTH_LOGOUT = "ON_AUTH_LOGOUT";
export const SET_SELECTED_USER = "SET_SELECTED_USER";